// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfjllnrximhdgqqelxar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmamxsbnJ4aW1oZGdxcWVseGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDcyNzQsImV4cCI6MjA2MjUyMzI3NH0.ldzDm-qknb1J6DWYndw4-LLPUR1ZClK2QVolAiQYT9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);